Proof of concept: Remote sync with `scp` (#1775)
Provide extensible implementation for further programs

Allow any command to be executed for syncing databases

Refactor remote process handling

Format files and add translations

Add remote open dialog

Remove braces in filename of remp database

Attempt sync with same key before using open dialog

Concurrently execute remote sync

so that the GUI thread is not blocked

Fix and add test for same and different key remote sync

Use config for remote sync parameters

Slightly refactor RemoteFileDialog

update translations

KeepassXC build seems to use a QT version below 5.11

Build failed with error: no member named 'WithoutBraces' in 'QUuid'

Fix remote sync tests

Use QScopedPointer for RemoteProcess

testRemoteSyncDatabaseRequiresPassword:
- need to processEvents twice
- trying to open database with the same key takes some time and the
 events fired afterwards may not be processed yet

testOpenRemoteDatabase:
- click button rather than trigger action
- need to set active window explicitly as it is empty after closing
 the dialog
- click OK button instead of hitting enter as there was a warning that
 the widget does not support enter

Rework remote sync widgets and save remote settings in config

Fix syncing: sync correct database

Get rid of one shot connections
Use disconnect correctly

mark database as remote to avoid saving it as last database

add status bar with progress bar to RemoteFileDialog

for indication that something is happening

update translations

mark remote database as remote in tab name

another example for download and upload

Minor cleanup

Update copyright of new files

Add missing translations

Add newline at the end of files

Add documentation for Remote Database Support

Avoid empty name for remote settings

Add database settings widget remote

remove DeleteableItemWidget

fix widget being locked if open dialog is closed

either via dialog close button or close window button

remove RemoteSettingsDialog

change remote tests to use database settings

Simplify remote open dialog

remove unused classes

Only mark database as modified if remote settings actually change

Cleanup after rebase

update translations

fix formatting

get remote tests to work on Mac OS

close popup again

clean up config

another mac os try

add debugging information during pipeline run for mac os failure

more logging

setActiveWindow

...

....

.....

.....

......

.......

deactivate `testRemoteSyncDatabaseRequiresPassword` on MacOS

as it messes with focus and leads to issues in following tests

deactivate `testRemoteSyncDatabaseSameKey` on MacOS

as it messes with focus and leads to issues in follow up tests

Revert deactivate test on MacOS