fix compilation on Qt < 5.12
The code uses 'QOperatingSystemVersion::MacOSBigSur' which doesn't exist in older
versions of Qt (it has been backported down to Qt 5.12). On older macos systems like
El Capitan the last supported version of Qt is 5.11.

This will fix compilation issue on such older systems

Compilation error was:
error: no member named 'MacOSBigSur' in 'QOperatingSystemVersion'